language: node_js
node_js:
  - 'node'

env:
  global:
    - CC_TEST_REPORTER_ID=da798c6484d3b717e6f05c3d9c639b4c9ee5cf61d05236131a0cdddb499e2577

script:
  - nyc yarn test

after_success:
  yarn coverage

services:
  - postgresql


before_script:
  - psql -c 'create database test2;' -U postgres
  - node ./table.js pg://postgres@127.0.0.1:5432/postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

